### ISSUE TITLE
Pitch Perfect Audio Recording

### ISSUE THREAD

**Issue by Sri5102** [Sri5102/iOS#1]
Hello,

Please help me with the issue on this iOS project.

**Comment by Sri5102** [comment]
[PitchPerfect.xcodeproj.zip](https://github.com/Sri5102/iOS/files/453542/PitchPerfect.xcodeproj.zip)

**Comment by Sri5102** [comment]
Please help resolving the issue and provide me feedback. Thanks

**Comment by chiragramani** [comment]
Hi..Can you please enclose your entire xcode project.I can only see "PitchPerfect.xcodeproj" but this project reads many files which are not included(eg. your swift files like appdelegate.swift etc)

**Comment by Sri5102** [comment]
Hi Chirag,

Please download the project and let me know what you get. Thanks.

[PitchPerfect.zip](https://github.com/Sri5102/iOS/files/453607/PitchPerfect.zip)

**Comment by chiragramani** [comment]
Hi..What I observed was in PlaySoundsVC-you have two properties  var recordedAudioURL: NSURL! and var racordedAudioURL:NSURL!  So, in recordsVC you were setting racordedAudioURL but was reading recordedAudioURL! thats why you were getting a fatal error since it is nil and cannot be unwrapped.


Second, since the segue connects the uibutton from recordviewVC to PlaySoundsVC-make the following modification:
override func prepareForSegue (segue: UIStoryboardSegue, sender: AnyObject?){
        if (segue.identifier == "stopRecording")
        {
            let playSoundsVC = segue.destinationViewController as! PlaySoundsViewController
            print("printing")
            let recordedAudioURL = audioRecorder.url
            playSoundsVC.recordedAudioURL = recordedAudioURL
        }
    }

**Comment by Sri5102** [comment]
Thank you so much for your great help. Now, issue is resolved after making changes on recordedAudioURL and segue. Thank you again.
